### ISSUE TITLE
Update the Readme file

### ISSUE THREAD

**Issue by Debajyati** [Debajyati/All-my-code-files-written-in-C-language#2]
Update the **_Readme_** including **all the newly included snippets** and  **correct the order of the list**.

> _**Please don't change any other file or snippets , as it may cause your PR to be avoided to be merged**_
Happy contributions!

**Comment by Debajyati** [comment]
Anyone who wishes to contribute must ask first to be assigned to this issue.

**Comment by ghost** [comment]
@Debajyati i want to work with assign it to me and please provide me your Twitter or discord I'd link to ask any question regarding it

**Comment by ghost** [comment]
@Debajyati please me your any social handles like discord id or Twitter for asking questions

**Comment by Debajyati** [comment]
This issue was solved by a contributor few days ago but he didn't do it properly ( I mean, he did include the names of the newly included files but didn't correct the order of the name of the files according the real order of the files in the programs folder). But still I merged it. Now I want you to make sure that you **please** check corrected the order before making a PR.

**And yes! Here is my Twitter ID - Check it out [https://twitter.com/ddebajyati?t=t4GNIgzi_ptMvtznIDLG9g&s=09](url)**

**Comment by ghost** [comment]
I got it i will try to make it better . This is my Twitter handle please
connect with me . Send me the follow then i will able to follow back you 👇

https://twitter.com/Ankitraj_rj17?t=hHKndItbtW5uwhBX0i62Bw&s=09

**Comment by ghost** [comment]
@Debajyati i have done it ✅ please check and merge it

**Comment by Debajyati** [comment]
Thank you, the changes are appreciated.
